### ISSUE TITLE
Give the header a Sec-* prefix

### ISSUE THREAD

**Issue by annevk** [TokenBinding/Internet-Drafts#1]
If you don't want this header to be spoofed from `XMLHttpRequest` or `fetch()`, please prefix it with `Sec-`.

**Comment by martinthomson** [comment]
That shouldn't be necessary in this case, because the Token-Binding header field is based on information that is extremely difficult (i.e., cryptographically impossible) for the site to access and spoof.

On the other hand, there could be value in having `XMLHttpRequest` or `fetch()` generate _different_ values for that header field in order to provide continuity of identity.

**Comment by balfanz** [comment]
Seems to me there is no harm in adding the Sec- prefix.

**Comment by martinthomson** [comment]
As I said, `Sec-` does no good. And - as I said - it might do harm.

**Comment by martinthomson** [comment]
To expand, if you can spoof this, then the crypto is busted.

What you _do_ want, is this to be treated like credentials. But you have that anyway.

**Comment by balfanz** [comment]
As to perhaps being useful:

The worry here is that I can serve you Javascript that will issue a fetch request to a server and make it look like you're controlling a keypair that you don't control (because my Javascript added the header with the signature). 

You're right that the signature is over something that I'm not supposed to know (the tls-unique), but the crypto doesn't guarantee that ("that" == "me not knowing the tls-unique"). The crypto only guarantees that I can't forge your signature on the tls-unique, and you can't forge mine. 

So I'm not sure what you mean by "if you can spoof this, the crypto is busted" - you're saying that then the signature scheme would be broken? Or that the attacker must have somehow figured out the tls-unique? I would agree with the latter, but then it seems like including the Sec- prefix would protect against such a case: Even if I knew your tls-unique with the server, I couldn't cause you to include my signature over that tls-unique.

So I tend to think that it could be useful (admittedly in the far-fetched case that I somehow knew your tls-unique without also MITM-ing your traffic to the server). 

I still don't understand why you think it could be harmful.

**Comment by martinthomson** [comment]
I think that the unforgivable property that is relevant here is that the signature is generated by a private key the spoofer didn't know. The value of tls-unique is, I agree, not a secret (even if its confidentiality is typically maintained).

**Comment by balfanz** [comment]
Ok, I think I understand what you're saying.

But do you agree that if I _do_ know the private key (because it's a key I control and that you have nothing to do with), then I could (assuming I also know your tls-unique) create a header that would make it look like you control this private key when you don't? That seems potentially harmful, no?

**Comment by martinthomson** [comment]
I don't generally try to solve that sort of problem. Don't let the bad guy use your keys is the rule I'd rely on here. But if the key will be seen as valid by the server, then, by definition, we should call it valid. If the server has state it has bound to that key, then you are either completely valid, our completely pwned.

In the end, I think that js should be able to generate these header fields, even if that provides no actual value with respect to the that model at hand, if only because it allows us to test our code. Also, there is work on js integrity that might make it interesting art some point (not that I think that work has legs, to be completely honest).

**Comment by annevk** [comment]
I think having this as defense-in-depth could be useful. Note that we similarly protect cookies. Testing is not a use case.

**Comment by leifj** [comment]
Folks - remember to mirror the discussion on the IETF-list. Discussions on github are not obviously covered by NOTE WELL.
