### ISSUE TITLE
One spec

### ISSUE THREAD

**Issue by martinthomson** [TokenBinding/Internet-Drafts#11]
This doesn't need to be two specifications.  On the contrary, the split is confusing.

**Comment by Andrei-Popov** [comment]
It is very likely that we'll want to use Token Binding with protocols other than HTTPS. Token Binding protocol message formats, key parameter negotiation, etc. are likely to be the same regardless of the application protocol, but the encapsulation of Token Binding messages in the application protocol will look different in each application protocol.

This is why I believe that keeping Token Binding protocol basics in a separate I-D is beneficial. In terms of presentation, we can certainly make improvements so that the two documents are more readable.

**Comment by martinthomson** [comment]
[YAGNI](https://en.wikipedia.org/wiki/You_aren%27t_gonna_need_it)

**Comment by leifj** [comment]
Folks - remember to mirror the discussion on the IETF-list. Discussions on github are not obviously covered by NOTE WELL.

**Comment by Andrei-Popov** [comment]
Given that we're going to author another spec OATHTB (that relies on TBPROTO), the separation into multiple I-Ds seems to provide more benefits than drawbacks. It is true that some content needs to be moved between specs for better cohesion; PR #16 addresses this.
