### ISSUE TITLE
TBPROTO: Not using uncompressed point from X9.62

### ISSUE THREAD

**Issue by martinthomson** [TokenBinding/Internet-Drafts#62]
The encoding of `ECPoint.point` in the spec varies from the definition in X9.62 unnecessarily.  The uncompressed point form is used by numerous specs.  The only cost to having this consistency is an extra octet (0x04).  For that low, low price, you can reference other specs rather than having to define the point encoding format yourself.

**Comment by b---c** [comment]
An alternative way to look at this is that the spec currently defines a more efficient encoding concisely inline in a couple sentences and has already produced independent interoperable implementations and doesn't require consulting an arcane document that isn't easily obtainable without paying $100.

**Comment by Andrei-Popov** [comment]
IMHO 0x04 is an arcane appendage used in TLS; there's hardly any reason to carry this baggage into new protocols. But if the WG really wants 0x04, I could live with that:).

**Comment by b---c** [comment]
I _do not_ want the arcane appendage that is 0x04

**Comment by nharper** [comment]
0x04 is an arcane appendage, but including it means that TB has a new custom format that it's using instead of using a standardized format. Where we can and where is reasonable I think we should be reusing existing standards instead of creating new ones. This seems like a place where the benefit of reusing an existing standard outweighs the cost of using it (a single byte).

(If there are concerns about having clear language defining it, we could say something like "An ECPoint.point is the X9.62 uncompressed point form. This is the octet 0x04 followed by [insert current text in the spec].")

**Comment by equalsJeffH** [comment]
seems to me @nharper has a good point.

**Comment by equalsJeffH** [comment]
Though, after further discussion and review by the WG of PR#82, we have decided to not do this. see thread on mailing list beginning here..

https://www.ietf.org/mail-archive/web/unbearable/current/msg01019.html
