### ISSUE TITLE
Include-Referer-Token-Binding-ID vs Token-Binding

### ISSUE THREAD

**Issue by annevk** [TokenBinding/Internet-Drafts#7]
Why not just `Include-Token-Binding`?

**Comment by balfanz** [comment]
Because the client will always include _some_ sort of token binding, in particular, the provided token binding. This header indicates that the client is supposed to include an _additional_ token binding, the referred token binding. 

Having said that, it's just a name, and I don't feel strongly about it. Do you?

**Comment by annevk** [comment]
I'd rather not have Referer [sic] again. Does this setup still work with multiple redirects?

**Comment by Andrei-Popov** [comment]
Closing since this looks like a dupe of issue #23.
