### ISSUE TITLE
Is CORS required?

### ISSUE THREAD

**Issue by annevk** [TokenBinding/Internet-Drafts#9]
It's not clear to me whether CORS is required for these cross-origin requests or if we also want it to work without CORS (when the response is opaque).

**Comment by balfanz** [comment]
Is this question similar to https://github.com/TokenBinding/Internet-Drafts/issues/10? If so, then yes, we should also talk about how to allow UAs to include referred token-bindings when POSTing to IdP, etc. But since that will all be handled by fetch(), that discussion should probably happen in the context of  https://github.com/whatwg/fetch/issues/30.
