### ISSUE TITLE
Explain necessity for signature on referred token binding

### ISSUE THREAD

**Issue by balfanz** [TokenBinding/Internet-Drafts#97]
We should explain that we're worried about clients being tricked into presenting a key that they don't control.

**Comment by Andrei-Popov** [comment]
This was already explained in several places:
"User Agent sends referred_token_binding to the Identity Provider in order to prove possession of the Token Binding key it uses with the Relying Party."
"Conveying referred Token Bindings in this fashion allows the Identity Provider to verify that the client controls the Token Binding key used with the Relying Party."
